# # services:
# #  laravel-docker:
# #   container_name: laravel-docker
# #   build: .
# #   volumes:
# #     - ./:/var/www/html/
# #   ports:
# #     - 9000:80

# #  mysql_db:
# #   image: mysql:8.0.33
# #   environment:
# #     MYSQL_ROOT_PASSWORD: root
# #     MYSQL_DATABASE: laravel_docker
# #   ports:
# #     - 3306:3306

# #  postgres_db:
# #   image: postgres:15.3
# #   environment:
# #     POSTGRES_USER: postgres
# #     POSTGRES_PASSWORD: postgres
# #     POSTGRES_DB: gsafe
# #   ports:
# #     - "5432:5432"
# version: '3'
# services:
#  laravel-docker:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     image: laravel-docker
#     container_name: laravel-docker
#     ports:
#       - "8080:80"
#     volumes:
#       - .:/var/www/html
#     environment:
#       POSTGRES_HOST: db
#       POSTGRES_PORT: 5432
#       POSTGRES_DB: gsafe
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#     depends_on:
#       - db

#  db:
#     image: postgres:15
#     container_name: postgres_db
#     environment:
#       POSTGRES_DB: gsafe
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:

version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_app
    container_name: laravel_app
    ports:
      - "8090:80"
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      POSTGRES_DB: gsafe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: gsafe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POSTGRES_HOST: '*'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
